---
- hosts: prod-server
  become: true
  tasks:

  - name: update the system
    command: sudo apt-get update

  - name: install docker 
    command: sudo apt install docker.io -y

  

  - name: docker remove
    command: sudo docker rm -f banking

  - name: docker run
    command: sudo docker run -itd -p 8081:8081 --name banking rakesh1299/banking:1.0
